name: Code Quality
on:
  - push
  - pull_request
jobs:
  check-lint:
    name: Check Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set Up NodeJS
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - name: Install Node Modules
        run: npm clean-install
      - name: Run Lint Check
        run: npm run check:lint
  check-style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set Up NodeJS
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - name: Install Node Modules
        run: npm clean-install
      - name: Run Lint Check
        run: npm run check:style
  check-types:
    name: Check Types
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set Up NodeJS
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - name: Install Node Modules
        run: npm clean-install
      - name: Run Lint Check
        run: npm run check:types
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set Up NodeJS
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - name: Install Node Modules
        run: npm clean-install
      - name: Run Tests
        run: npm run test:ci
